export const companies = [
  {
    id: "1",
    name: "Google",
    role: "Software Engineer",
    package: "₹25 LPA",
    deadline: "2024-01-15",
    status: "open",
    description: "Join Google as a Software Engineer and work on cutting-edge technology.",
    requirements: ["B.Tech/M.Tech in CS/IT", "Strong programming skills", "CGPA > 8.0"],
    rounds: ["Online Coding Round", "Technical Interview 1", "Technical Interview 2", "HR Interview"],
  },
  {
    id: "2",
    name: "Microsoft",
    role: "Product Manager",
    package: "₹22 LPA",
    deadline: "2024-01-20",
    status: "open",
    description: "Lead product development at Microsoft.",
    requirements: ["Any Engineering degree", "Leadership experience", "CGPA > 7.5"],
    rounds: ["Aptitude + Product Thinking", "Case Study Presentation", "Panel Interview", "HR Interview"],
  },
  {
    id: "3",
    name: "Amazon",
    role: "Data Scientist",
    package: "₹20 LPA",
    deadline: "2024-01-10",
    status: "closed",
    description: "Work with big data and machine learning at Amazon.",
    requirements: ["B.Tech/M.Tech", "Python/R skills", "CGPA > 8.5"],
    rounds: ["Online Assessment (ML + Stats)", "Tech Interview", "Bar Raiser"],
  },
] as const
